version: '3'

services:
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  app:
    build:
      context: .
      dockerfile: DZ6_Chubar_OO_Dockf.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo-data:
